# Generated by Django 5.2.2 on 2026-07-01 18:39

from django.db import migrations, models


DEFAULT_SITE_TYPE_ICONS = (
    (
        "beach",
        ["coastal", "beach", "shore", "shoreline", "estuary", "tidal stream", "tidal"],
    ),
    ("calculator", ["calculated", "model", "modeled"]),
    ("fountain", ["spring", "seep"]),
    ("gate", ["dry dam release", "dry dam", "dam", "weir", "sluice"]),
    (
        "gauge",
        ["stream gage", "stream gauge", "flow station", "gage", "gauge", "flume"],
    ),
    ("grass", ["wetland", "marsh", "swamp", "bog", "fen"]),
    ("home", ["house", "building"]),
    ("hydro-power", ["hydropower", "hydro power", "power generation"]),
    (
        "map-marker-radius-outline",
        ["monitoring site", "monitoring station", "site", "station"],
    ),
    (
        "pipe-disconnected",
        ["storm sewer", "storm drain", "stormwater", "storm water", "drainage"],
    ),
    ("road-variant", ["pavement", "road crossing", "road"]),
    ("snowflake", ["snow", "snowpack", "snotel", "ice", "glacier"]),
    ("sprinkler", ["irrigation pivot", "irrigation", "irrigated"]),
    ("terrain", ["soil hole", "soil", "terrain", "land"]),
    (
        "test-tube",
        [
            "water quality sample",
            "grab sample",
            "laboratory",
            "chemistry",
            "sample",
            "sampling",
            "lab",
        ],
    ),
    ("thermometer-water", ["water temperature", "temperature", "thermal"]),
    (
        "vector-polyline",
        ["ditch", "canal", "channel", "aqueduct", "conveyance"],
    ),
    ("water", ["creek", "river", "stream", "brook", "tributary"]),
    (
        "water-check-outline",
        [
            "water quality station",
            "water quality",
            "quality sensor",
            "sonde",
            "turbidity",
            "conductivity",
        ],
    ),
    ("water-pump", ["pump station", "lift station", "pump", "pumping"]),
    (
        "water-well",
        [
            "groundwater well",
            "observation well",
            "ground water",
            "groundwater",
            "borehole",
            "aquifer",
            "piezometer",
            "well",
        ],
    ),
    (
        "waves",
        ["reservoir lake", "reservoir", "lake", "pond", "pool", "impoundment"],
    ),
    (
        "waves-arrow-right",
        ["reservoir release", "release", "outflow", "spillway"],
    ),
    (
        "weather-cloudy",
        ["weather station", "atmosphere", "weather", "meteorological", "meteorology"],
    ),
)


def create_default_site_type_icons(apps, schema_editor):
    site_type_icon = apps.get_model("web", "SiteTypeIcon")
    site_type_icon.objects.bulk_create(
        [
            site_type_icon(icon=icon, site_types=site_types)
            for icon, site_types in DEFAULT_SITE_TYPE_ICONS
        ]
    )


def remove_default_site_type_icons(apps, schema_editor):
    site_type_icon = apps.get_model("web", "SiteTypeIcon")
    site_type_icon.objects.filter(
        icon__in=[icon for icon, _ in DEFAULT_SITE_TYPE_ICONS]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTypeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("beach", "Beach"),
                            ("calculator", "Calculator"),
                            ("fountain", "Fountain"),
                            ("gate", "Gate"),
                            ("gauge", "Gauge"),
                            ("grass", "Grass"),
                            ("home", "Home"),
                            ("hydro-power", "Hydropower"),
                            ("map-marker-radius-outline", "Site marker"),
                            ("pipe-disconnected", "Disconnected pipe"),
                            ("road-variant", "Road"),
                            ("snowflake", "Snowflake"),
                            ("sprinkler", "Sprinkler"),
                            ("terrain", "Terrain"),
                            ("test-tube", "Test tube"),
                            ("thermometer-water", "Water thermometer"),
                            ("vector-polyline", "Polyline"),
                            ("water", "Water"),
                            ("water-check-outline", "Water quality"),
                            ("water-pump", "Water pump"),
                            ("water-well", "Water well"),
                            ("waves", "Waves"),
                            ("waves-arrow-right", "Waves with right arrow"),
                            ("weather-cloudy", "Cloudy weather"),
                        ],
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "site_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Site type names or keywords that should use this icon.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Type Icon",
                "verbose_name_plural": "Site Type Icons",
                "ordering": ("id",),
            },
        ),
        migrations.RunPython(
            create_default_site_type_icons,
            remove_default_site_type_icons,
        ),
    ]
