# Generated by Django 5.2.2 on 2026-07-01 18:39

from django.db import migrations, models


DEFAULT_SITE_TYPE_ICONS = (
    (
        "beach",
        ["Coastal", "Beach", "Shore", "Shoreline", "Estuary", "Tidal Stream", "Tidal"],
    ),
    ("calculator", ["Modeled / Calculated", "Calculated", "Model", "Modeled"]),
    ("fountain", ["Spring", "Seep"]),
    (
        "gate",
        [
            "Dam / Control Structure",
            "Dry Dam Release",
            "Dry Dam",
            "Dam",
            "Weir",
            "Sluice",
        ],
    ),
    (
        "gauge",
        [
            "Gaging Station",
            "Stream Gage",
            "Stream Gauge",
            "Flow Station",
            "Gage",
            "Gauge",
            "Flume",
        ],
    ),
    ("grass", ["Wetland", "Marsh", "Swamp", "Bog", "Fen"]),
    ("home-outline", ["House", "Building"]),
    ("hydro-power", ["Hydropower", "Hydro Power", "Power Generation"]),
    ("image-filter-hdr", ["Land", "Land Surface", "Upland"]),
    (
        "map-marker",
        [
            "Site — Default Fallback",
            "Monitoring Site",
            "Monitoring Station",
            "Site",
            "Station",
        ],
    ),
    (
        "pipe-disconnected",
        ["Stormwater", "Storm Sewer", "Storm Drain", "Storm Water", "Drainage"],
    ),
    ("road-variant", ["Pavement", "Road Crossing", "Road"]),
    ("snowflake", ["Snow / Ice", "Snow", "Snowpack", "Snotel", "Ice", "Glacier"]),
    ("sprinkler", ["Irrigation", "Irrigation Pivot", "Irrigated"]),
    ("terrain", ["Soil", "Soil Hole", "Terrain"]),
    (
        "test-tube",
        [
            "Discrete Sample",
            "Water Quality Sample",
            "Grab Sample",
            "Laboratory",
            "Chemistry",
            "Sample",
            "Sampling",
            "Lab",
        ],
    ),
    (
        "vector-polyline",
        ["Conveyance", "Ditch", "Canal", "Channel", "Aqueduct"],
    ),
    ("water", ["Stream", "Creek", "River", "Brook", "Tributary"]),
    (
        "water-check",
        [
            "Water Quality Station",
            "Water Quality",
            "Quality Sensor",
            "Sonde",
            "Turbidity",
            "Conductivity",
        ],
    ),
    ("water-pump", ["Pump Station", "Lift Station", "Pump", "Pumping"]),
    (
        "water-well",
        [
            "Groundwater Well",
            "Observation Well",
            "Ground Water",
            "Groundwater",
            "Borehole",
            "Aquifer",
            "Piezometer",
            "Well",
        ],
    ),
    (
        "waves",
        ["Reservoir / Lake", "Reservoir", "Lake", "Pond", "Pool", "Impoundment"],
    ),
    (
        "waves-arrow-right",
        ["Reservoir Release", "Release", "Outflow", "Spillway"],
    ),
    (
        "weather-cloudy",
        [
            "Weather / Atmosphere",
            "Weather Station",
            "Atmosphere",
            "Weather",
            "Meteorological",
            "Meteorology",
        ],
    ),
)


def create_default_site_type_icons(apps, schema_editor):
    site_type_icon = apps.get_model("web", "SiteTypeIcon")
    site_type_icon.objects.bulk_create(
        [
            site_type_icon(icon=icon, site_types=site_types)
            for icon, site_types in DEFAULT_SITE_TYPE_ICONS
        ],
        ignore_conflicts=True,
    )


def remove_default_site_type_icons(apps, schema_editor):
    site_type_icon = apps.get_model("web", "SiteTypeIcon")
    site_type_icon.objects.filter(
        icon__in=[icon for icon, _ in DEFAULT_SITE_TYPE_ICONS]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTypeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("beach", "Beach"),
                            ("calculator", "Calculator"),
                            ("fountain", "Fountain"),
                            ("gate", "Gate"),
                            ("gauge", "Gauge"),
                            ("grass", "Grass"),
                            ("home-outline", "Home"),
                            ("hydro-power", "Hydropower"),
                            ("image-filter-hdr", "Land"),
                            ("map-marker", "Site marker"),
                            ("pipe-disconnected", "Disconnected pipe"),
                            ("road-variant", "Road"),
                            ("snowflake", "Snowflake"),
                            ("sprinkler", "Sprinkler"),
                            ("terrain", "Terrain"),
                            ("test-tube", "Test tube"),
                            ("vector-polyline", "Polyline"),
                            ("water", "Water"),
                            ("water-check", "Water quality"),
                            ("water-pump", "Water pump"),
                            ("water-well", "Water well"),
                            ("waves", "Waves"),
                            ("waves-arrow-right", "Waves with right arrow"),
                            ("weather-cloudy", "Cloudy weather"),
                        ],
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "site_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Site type names or keywords that should use this icon.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Type Icon",
                "verbose_name_plural": "Site Type Icons",
                "ordering": ("id",),
            },
        ),
        migrations.RunPython(
            create_default_site_type_icons,
            remove_default_site_type_icons,
        ),
    ]
