# Generated by Django 5.2.2 on 2026-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_permission_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource_type',
            field=models.CharField(choices=[('*', 'All'), ('APIKey', 'API Key'), ('Role', 'Role'), ('Collaborator', 'Collaborator'), ('Thing', 'Thing'), ('Datastream', 'Datastream'), ('Observation', 'Observation'), ('Sensor', 'Sensor'), ('ObservedProperty', 'Observed Property'), ('ProcessingLevel', 'Processing Level'), ('Unit', 'Unit'), ('ResultQualifier', 'Result Qualifier'), ('ETL', 'ETL'), ('DataProduct', 'Data Product'), ('DataMonitoring', 'Data Monitoring')], max_length=50),
        ),
    ]
