# Generated by Django 6.0.7 on 2026-07-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def split_key_prefix(apps, schema_editor):
    ServiceAccount = apps.get_model('iam', 'ServiceAccount')
    for account in ServiceAccount.objects.all():
        prefix, _, key_hash = account.key_hash.partition('$')
        account.key_prefix = prefix
        account.key_hash = key_hash
        account.save(update_fields=['key_prefix', 'key_hash'])


def reverse_split_key_prefix(apps, schema_editor):
    ServiceAccount = apps.get_model('iam', 'ServiceAccount')
    for account in ServiceAccount.objects.all():
        account.key_hash = f"{account.key_prefix}${account.key_hash}"
        account.save(update_fields=['key_hash'])


def add_service_account_email(apps, schema_editor):
    ServiceAccount = apps.get_model('iam', 'ServiceAccount')
    domain = getattr(settings, 'SERVICE_ACCOUNT_EMAIL_DOMAIN', 'hydroserver.local')
    for account in ServiceAccount.objects.all():
        account.email = f"{account.key_prefix}@service-accounts.{domain}"
        account.save(update_fields=['email'])


def reverse_add_service_account_email(apps, schema_editor):
    ServiceAccount = apps.get_model('iam', 'ServiceAccount')
    ServiceAccount.objects.update(email='')


def create_collaborators_for_service_accounts(apps, schema_editor):
    ServiceAccount = apps.get_model('iam', 'ServiceAccount')
    Collaborator = apps.get_model('iam', 'Collaborator')
    for account in ServiceAccount.objects.all():
        Collaborator.objects.create(
            workspace_id=account.workspace_id,
            service_account_id=account.id,
            role_id=account.role_id,
        )


def reverse_create_collaborators_for_service_accounts(apps, schema_editor):
    Collaborator = apps.get_model('iam', 'Collaborator')
    Collaborator.objects.filter(service_account__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_alter_permission_resource_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIKey',
            new_name='ServiceAccount',
        ),
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'verbose_name': 'Service Account', 'verbose_name_plural': 'Service Accounts'},
        ),
        migrations.RenameField(
            model_name='serviceaccount',
            old_name='expires_at',
            new_name='key_expires_at',
        ),
        migrations.RenameField(
            model_name='serviceaccount',
            old_name='last_used',
            new_name='last_used_at',
        ),
        migrations.RenameField(
            model_name='serviceaccount',
            old_name='hashed_key',
            new_name='key_hash',
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='key_prefix',
            field=models.CharField(max_length=12, editable=False, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(split_key_prefix, reverse_split_key_prefix),
        migrations.AlterField(
            model_name='serviceaccount',
            name='key_prefix',
            field=models.CharField(max_length=12, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='key_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=254, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(add_service_account_email, reverse_add_service_account_email),
        migrations.AlterField(
            model_name='serviceaccount',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='key_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),

        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='iam.serviceaccount'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            create_collaborators_for_service_accounts,
            reverse_create_collaborators_for_service_accounts,
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='role',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_assignments', to='iam.role'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='iam.workspace'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service_account__isnull', True), ('user__isnull', False)), models.Q(('service_account__isnull', False), ('user__isnull', True)), _connector='OR'), name='collaborator_principal_is_user_xor_service_account'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workspace', 'user'), name='unique_workspace_user_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('service_account__isnull', False)), fields=('workspace', 'service_account'), name='unique_workspace_service_account_collaborator'),
        ),

        migrations.AlterField(
            model_name='serviceaccount',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='service_accounts', to='iam.workspace'),
        ),
    ]
