# Generated by Django 6.0.7 on 2026-07-22 16:48

import core.iam.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_rename_apikey_serviceaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacedeleteconfirmation',
            name='workspace',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.iam.models.user.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_type',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_apikey_role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_user_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ownership_allowed',
        ),
        migrations.RemoveField(
            model_name='workspacetransferconfirmation',
            name='initiated',
        ),
        migrations.AddField(
            model_name='permission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owned_workspace_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='iam.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('role', 'resource_type'), name='unique_role_resource_type'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('name',), name='unique_global_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'name'), name='unique_workspace_role_name'),
        ),
        migrations.DeleteModel(
            name='WorkspaceDeleteConfirmation',
        ),
    ]
