# Generated by Django 6.0.7 on 2026-07-23 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_remove_workspacedeleteconfirmation_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
