# Generated by Django 6.0.7 on 2026-09-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0010_rename_sensor_permission'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='collaborator',
            name='unique_workspace_user_collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workspace', 'user'), name='unique_workspace_user_collaborator', violation_error_message='This account already collaborates on the workspace'),
        ),
        migrations.AlterConstraint(
            model_name='collaborator',
            name='unique_workspace_service_account_collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('service_account__isnull', False)), fields=('workspace', 'service_account'), name='unique_workspace_service_account_collaborator', violation_error_message='This account already collaborates on the workspace'),
        ),
    ]
