# Generated by Django 5.2.2 on 2026-04-03 16:24

import uuid6
import core.iam.models.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestration', '0001_initial'),
        ('sta', '0007_remove_thingfileattachment_download_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orchestration.task')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_tasks', to='sta.thing')),
            ],
            bases=('orchestration.task', core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='MonitoredDatastream',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='sta.datastream')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_datastreams', to='monitoring.monitoringtask')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('range', 'Allowed Range'), ('rate_of_change', 'Rate Of Change'), ('persistence', 'Persistence'), ('missing_data', 'Missing Data')], max_length=255)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('max_change', models.FloatField(blank=True, null=True)),
                ('max_persistence_count', models.IntegerField(blank=True, null=True)),
                ('window', models.IntegerField(blank=True, null=True)),
                ('window_units', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=255, null=True)),
                ('monitored_datastream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='monitoring.monitoreddatastream')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('monitored_datastream', 'rule_type'), name='unique_monitoring_rule_type_per_datastream')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringNotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='monitoring.monitoringtask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'email'), name='unique_monitoring_notification_recipient_email')],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoreddatastream',
            constraint=models.UniqueConstraint(fields=('task', 'datastream'), name='unique_monitored_datastream_per_task'),
        ),
    ]
