# Generated by Django 5.2.2 on 2026-04-13 16:00

import core.iam.models.utils
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestration', '0001_initial'),
        ('sta', '0007_remove_thingfileattachment_download_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orchestration.task')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_tasks', to='sta.thing')),
            ],
            bases=('orchestration.task', core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='RatingCurve',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('fitting_method', models.CharField(choices=[('linear', 'Linear'), ('power_law', 'Power Law'), ('polynomial', 'Polynomial')], max_length=20)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_curves', to='sta.thing')),
            ],
            bases=(models.Model, core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='DataProductTransformation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('transformation_type', models.CharField(choices=[('rating_curve', 'Rating Curve'), ('expression', 'Expression'), ('composite_expression', 'Composite Expression'), ('aggregation', 'Aggregation')], max_length=255)),
                ('formula', models.TextField(blank=True, null=True)),
                ('output_interval_units', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=255, null=True)),
                ('output_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone_type', models.CharField(blank=True, choices=[('utc', 'Utc'), ('offset', 'Offset'), ('iana', 'Iana')], max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregation_method', models.CharField(blank=True, choices=[('simple_mean', 'Simple Mean'), ('sum', 'Sum'), ('min_value', 'Min Value'), ('max_value', 'Max Value'), ('first_value', 'First Value'), ('last_value', 'Last Value')], max_length=255, null=True)),
                ('max_gap_interval_units', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=255, null=True)),
                ('max_gap_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('min_values', models.PositiveIntegerField(blank=True, null=True)),
                ('output_datastream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_transformation', to='sta.datastream')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='products.dataproducttask')),
                ('rating_curve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transformations', to='products.ratingcurve')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCurvePoint',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField()),
                ('rating_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='products.ratingcurve')),
            ],
            options={
                'ordering': ['input_value'],
            },
        ),
        migrations.CreateModel(
            name='DataProductTransformationInput',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('variable_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_transformation_inputs', to='sta.datastream')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_datastreams', to='products.dataproducttransformation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('variable_name__isnull', False)), fields=('transformation', 'variable_name'), name='unique_data_product_transformation_input_variable')],
            },
        ),
    ]
