# Generated by Django 5.2.2 on 2026-04-06 03:00

import core.iam.models.utils
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestration', '0001_initial'),
        ('sta', '0007_remove_thingfileattachment_download_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProductTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orchestration.task')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_tasks', to='sta.thing')),
            ],
            bases=('orchestration.task', core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('breakpoint_variable', models.CharField(blank=True, max_length=255, null=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='sta.thing')),
            ],
            bases=(models.Model, core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='ExpressionSegment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='products.expression')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCurve',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_curves', to='sta.thing')),
            ],
            bases=(models.Model, core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='DataProductOutputMapping',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('transformation_type', models.CharField(choices=[('rating_curve', 'Rating Curve'), ('expression', 'Expression'), ('temporal_aggregation', 'Temporal Aggregation')], max_length=255)),
                ('aggregation_method', models.CharField(blank=True, choices=[('simple_mean', 'Simple Mean'), ('weighted_mean', 'Weighted Mean'), ('min_value', 'Min Value'), ('max_value', 'Max Value'), ('first_value', 'First Value'), ('last_value', 'Last Value')], max_length=255, null=True)),
                ('aggregation_period', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=255, null=True)),
                ('aggregation_timezone_type', models.CharField(blank=True, choices=[('utc', 'Utc'), ('offset', 'Offset'), ('iana', 'Iana')], max_length=255, null=True)),
                ('aggregation_timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregation_min_coverage', models.FloatField(blank=True, null=True)),
                ('alignment_tolerance', models.PositiveIntegerField(blank=True, null=True)),
                ('output_datastream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_mapping', to='sta.datastream')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='products.dataproducttask')),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='products.expression')),
                ('rating_curve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='products.ratingcurve')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCurvePoint',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('input_value', models.FloatField()),
                ('output_value', models.FloatField(blank=True, null=True)),
                ('rating_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='products.ratingcurve')),
            ],
            options={
                'ordering': ['input_value'],
            },
        ),
        migrations.CreateModel(
            name='RatingCurveSegment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('fitting_method', models.CharField(choices=[('linear', 'Linear'), ('power_law', 'Power Law'), ('polynomial', 'Polynomial'), ('spline', 'Spline')], max_length=20)),
                ('rating_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='products.ratingcurve')),
            ],
        ),
        migrations.CreateModel(
            name='DataProductInputMapping',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('variable_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_product_input_mappings', to='sta.datastream')),
                ('output_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_mappings', to='products.dataproductoutputmapping')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('variable_name__isnull', False)), fields=('output_mapping', 'variable_name'), name='unique_data_product_input_mapping_variable')],
            },
        ),
    ]
