# Generated by Django 5.2.2 on 2026-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproducttransformation',
            name='aggregation_method',
            field=models.CharField(blank=True, choices=[('mean', 'Mean'), ('sum', 'Sum'), ('min', 'Min'), ('max', 'Max'), ('first', 'First'), ('last', 'Last'), ('time_weighted_mean', 'Time Weighted Mean')], max_length=255, null=True),
        ),
    ]
