# Generated by Django 5.2.2 on 2026-07-29 18:45

from django.db import migrations, models


def merge_composite_expression_into_derivation(apps, schema_editor):
    """
    'composite_expression' is retired in favor of a single 'derivation' type that
    accepts one or more inputs. Existing composite_expression rows become derivation
    rows (their now-meaningless output_interval fields are cleared). Plain 'expression'
    rows are renamed to 'derivation' too, since that's the same type under its new
    name. Every derivation row (old and converted) defaults to stop_on_no_data=False,
    stop_on_error=False, since neither transformation_type ever halted output on bad
    data before, and the new columns' schema default of True would.
    """

    DataProductTransformation = apps.get_model("products", "DataProductTransformation")

    DataProductTransformation.objects.filter(transformation_type="composite_expression").update(
        transformation_type="derivation",
        output_interval_units=None,
        output_interval=None,
    )

    DataProductTransformation.objects.filter(transformation_type="expression").update(
        transformation_type="derivation",
    )

    DataProductTransformation.objects.filter(transformation_type="derivation").update(
        stop_on_no_data=False,
        stop_on_error=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_dataproducttransformation_aggregation_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproducttransformation',
            name='max_gap_interval',
        ),
        migrations.RemoveField(
            model_name='dataproducttransformation',
            name='max_gap_interval_units',
        ),
        migrations.AddField(
            model_name='dataproducttransformation',
            name='stop_on_error',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='dataproducttransformation',
            name='stop_on_no_data',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='dataproducttransformation',
            name='transformation_type',
            field=models.CharField(choices=[('rating_curve', 'Rating Curve'), ('derivation', 'Derivation'), ('aggregation', 'Aggregation')], max_length=255),
        ),
        migrations.RunPython(
            merge_composite_expression_into_derivation,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
