# Generated by Django 6.0.7 on 2026-09-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_thing_monitoring_site'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ratingcurvepoint',
            constraint=models.UniqueConstraint(fields=('rating_curve', 'input_value'), name='unique_rating_curve_point_input_value', violation_error_message='A point with this input_value already exists on this rating curve.'),
        ),
    ]
