# Generated by Django 5.2.2 on 2026-06-10 22:33

import core.iam.models.utils
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sta', '0007_remove_thingfileattachment_download_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCHistory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phenomenon_time_start', models.DateTimeField(blank=True, null=True)),
                ('phenomenon_time_end', models.DateTimeField(blank=True, null=True)),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('managed_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('managed_datastream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_history', to='sta.datastream')),
                ('source_datastream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_source_histories', to='sta.datastream')),
            ],
            bases=(models.Model, core.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name='QCSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phenomenon_time_start', models.DateTimeField()),
                ('phenomenon_time_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('committed', 'Committed')], default='in_progress', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_checksum', models.CharField(max_length=64)),
                ('managed_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_sessions', to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quality.qchistory')),
            ],
            options={
                'ordering': ['phenomenon_time_start'],
            },
        ),
        migrations.CreateModel(
            name='QCOperation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('operation_type', models.CharField(choices=[('SELECTION', 'Selection'), ('VALUE_THRESHOLD', 'Value Threshold'), ('DATETIME_RANGE', 'Datetime Range'), ('CHANGE', 'Change'), ('RATE_OF_CHANGE', 'Rate Of Change'), ('FIND_GAPS', 'Find Gaps'), ('PERSISTENCE', 'Persistence'), ('ADD_POINTS', 'Add Points'), ('CHANGE_VALUES', 'Change Values'), ('ASSIGN_VALUES_BULK', 'Assign Values Bulk'), ('DELETE_POINTS', 'Delete Points'), ('DRIFT_CORRECTION', 'Drift Correction'), ('INTERPOLATE', 'Interpolate'), ('SHIFT_DATETIMES', 'Shift Datetimes'), ('FILL_GAPS', 'Fill Gaps'), ('ASSIGN_DATETIMES_BULK', 'Assign Datetimes Bulk')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='quality.qcsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QCSessionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='quality.qcsession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='quality.qcsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qcsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('history',), name='unique_in_progress_session_per_history'),
        ),
        migrations.AddConstraint(
            model_name='qcoperation',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_qc_operation_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='qcsessiondependency',
            constraint=models.UniqueConstraint(fields=('session', 'dependency'), name='unique_qc_session_dependency'),
        ),
    ]
