# Generated by Django 5.2b1 on 2025-04-15 21:58

import domains.iam.models.utils
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataArchive",
            fields=[
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interval_units",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("crontab", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("paused", models.BooleanField(default=False)),
                ("last_run_successful", models.BooleanField(blank=True, null=True)),
                ("last_run_message", models.TextField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interval_units",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("crontab", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("paused", models.BooleanField(default=False)),
                ("last_run_successful", models.BooleanField(blank=True, null=True)),
                ("last_run_message", models.TextField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="OrchestrationSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("orchestration_system_type", models.CharField(max_length=255)),
            ],
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
    ]
