# Generated by Django 5.2.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0005_fix_celery_task_names"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["task", "-started_at"],
                name="etl_taskrun_task_started_idx",
            ),
        ),
    ]
