# Generated by Django 5.2b1 on 2025-04-15 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etl", "0001_initial"),
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataarchive",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_archives",
                to="iam.workspace",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_sources",
                to="iam.workspace",
            ),
        ),
        migrations.AddField(
            model_name="orchestrationsystem",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orchestration_systems",
                to="iam.workspace",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="orchestration_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_sources",
                to="etl.orchestrationsystem",
            ),
        ),
        migrations.AddField(
            model_name="dataarchive",
            name="orchestration_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="data_archives",
                to="etl.orchestrationsystem",
            ),
        ),
    ]
