# Generated by Django 5.2.5 on 2025-11-25 16:26

import django.db.models.deletion
import domains.iam.models.utils
import uuid6
from django.db import migrations, models
from django.utils import timezone


def update_settings_fields(apps, schema_editor):
    DataSource = apps.get_model("etl", "DataSource")
    OrchestrationSystem = apps.get_model("etl", "OrchestrationSystem")
    DataConnection = apps.get_model("etl", "DataConnection")
    Task = apps.get_model("etl", "Task")
    TaskMapping = apps.get_model("etl", "TaskMapping")
    TaskMappingPath = apps.get_model("etl", "TaskMappingPath")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")

    for data_source in DataSource.objects.all():
        orchestration_system = OrchestrationSystem.objects.get(id=data_source.orchestration_system_id)

        settings = data_source.settings or {}
        data_connection = DataConnection.objects.create(
            name=data_source.name,
            data_connection_type=data_source.settings.get("type", "ETL"),
            workspace=data_source.workspace,
            extractor_type=data_source.settings.get("extractor", {}).get("type"),
            extractor_settings={
                k: v for k, v in data_source.settings.get("extractor", {}).items() if k != "type"
            },
            transformer_type=data_source.settings.get("transformer", {}).get("type"),
            transformer_settings={
                k: v for k, v in data_source.settings.get("transformer", {}).items() if k != "type"
            },
            loader_type=data_source.settings.get("loader", {}).get("type"),
            loader_settings={
                k: v for k, v in data_source.settings.get("loader", {}).items() if k != "type"
            },
        )

        for payload in settings.get("payloads", []):
            task = Task.objects.create(
                name=payload.get("name", "ETL Task"),
                workspace=data_source.workspace,
                data_connection=data_connection,
                orchestration_system=orchestration_system,
                paused=data_source.paused,
                next_run_at=data_source.next_run,
                extractor_variables=payload.get("extractorVariables", {}),
                transformer_variables=payload.get("transformerVariables", {}),
                loader_variables=payload.get("loaderVariables", {}),
            )

            if data_source.crontab is not None or data_source.interval is not None:
                periodic_task = PeriodicTask.objects.create(
                    name=f"{task.name} — {str(task.id)}",
                    task="etl.tasks.run_etl_task",
                    kwargs=f'{{"task_id": "{str(task.id)}"}}',
                    enabled=not data_source.paused and not orchestration_system,
                    last_run_at=data_source.last_run,
                    date_changed=timezone.now(),
                    start_time=data_source.start_time or timezone.now(),
                    expire_seconds=3600
                )
                if data_source.interval is not None:
                    interval_schedule = IntervalSchedule.objects.create(
                        every=data_source.interval,
                        period=data_source.interval_units,
                    )
                    periodic_task.interval = interval_schedule

                elif data_source.crontab is not None:
                    crontab_split = data_source.crontab.split(" ")
                    crontab_schedule = CrontabSchedule.objects.create(
                        minute=crontab_split[0],
                        hour=crontab_split[1],
                        day_of_week=crontab_split[2],
                        day_of_month=crontab_split[3],
                        month_of_year=crontab_split[4],
                        timezone="UTC"
                    )
                    periodic_task.crontab = crontab_schedule

                periodic_task.save()
                task.periodic_task = periodic_task

            for mapping_setting in payload.get("mappings", []):
                mapping = TaskMapping.objects.create(
                    task=task,
                    source_identifier=mapping_setting.get("sourceIdentifier")
                )

                for path_setting in mapping_setting.get("paths", []):
                    TaskMappingPath.objects.create(
                        task_mapping=mapping,
                        target_identifier=path_setting["targetIdentifier"],
                        data_transformations=path_setting.get("dataTransformations", []),
                    )

            task.save()


def reverse_update_settings_fields(apps, schema_editor):
    DataSource = apps.get_model("etl", "DataSource")
    OrchestrationSystem = apps.get_model("etl", "OrchestrationSystem")
    DataConnection = apps.get_model("etl", "DataConnection")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    Task = apps.get_model("etl", "Task")
    TaskMapping = apps.get_model("etl", "TaskMapping")
    TaskMappingPath = apps.get_model("etl", "TaskMappingPath")

    for data_connection in DataConnection.objects.all():
        reconstructed = {}

        if data_connection.data_connection_type:
            reconstructed["type"] = data_connection.data_connection_type

        if data_connection.extractor_type:
            reconstructed["extractor"] = {
                "type": data_connection.extractor_type,
                **(data_connection.extractor_settings or {}),
            }

        if data_connection.transformer_type:
            reconstructed["transformer"] = {
                "type": data_connection.transformer_type,
                **(data_connection.transformer_settings or {}),
            }

        if data_connection.loader_type:
            reconstructed["loader"] = {
                "type": data_connection.loader_type,
                **(data_connection.loader_settings or {}),
            }

        payloads = []
        tasks = Task.objects.filter(data_connection=data_connection)
        orchestration_system = None

        paused = None
        next_run = None
        start_time = None
        crontab = None
        interval = None
        interval_units = None

        if not tasks:
            continue

        for task in tasks:
            orchestration_system = task.orchestration_system

            payload = {
                "name": task.name,
                "extractorVariables": task.extractor_variables or {},
                "transformerVariables": task.transformer_variables or {},
                "loaderVariables": task.loader_variables or {},
                "mappings": [],
            }

            mappings = TaskMapping.objects.filter(task=task)
            for mapping in mappings:
                mapping_data = {
                    "sourceIdentifier": mapping.source_identifier,
                    "paths": [],
                }

                paths = TaskMappingPath.objects.filter(task_mapping=mapping)
                for path in paths:
                    mapping_data["paths"].append(
                        {
                            "targetIdentifier": path.target_identifier,
                            "dataTransformations": path.data_transformations or [],
                        }
                    )

                payload["mappings"].append(mapping_data)

            payloads.append(payload)

            try:
                periodic_task = task.periodic_task
            except PeriodicTask.DoesNotExist:
                periodic_task = None

            if periodic_task:
                paused = task.paused
                next_run = task.next_run_at
                start_time = task.periodic_task.start_time
                crontab_record = None
                interval_record = None

                if task.periodic_task.crontab:
                    minute = task.periodic_task.crontab.minute,
                    hour = task.periodic_task.crontab.hour,
                    day_of_week = task.periodic_task.crontab.day_of_week,
                    day_of_month = task.periodic_task.crontab.day_of_month,
                    month_of_year = task.periodic_task.crontab.month_of_year,
                    crontab = f"{minute[0]} {hour[0]} {day_of_week[0]} {day_of_month[0]} {month_of_year[0]}"
                    crontab_record = task.periodic_task.crontab

                elif task.periodic_task.interval:
                    interval = task.periodic_task.interval.every
                    interval_units = task.periodic_task.interval.period
                    interval_record = task.periodic_task.interval

                task.periodic_task.delete()

                if crontab_record:
                    crontab_record.delete()

                if interval_record:
                    interval_record.delete()

        if payloads:
            reconstructed["payloads"] = payloads

        DataSource.objects.create(
            name=data_connection.name,
            workspace=data_connection.workspace,
            settings=reconstructed,
            crontab=crontab,
            interval=interval,
            interval_units=interval_units,
            paused=paused if paused is not None else True,
            last_run=None,
            next_run=next_run,
            start_time=start_time,
            orchestration_system=orchestration_system,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("etl", "0002_initial"),
        ("iam", "0003_role_is_apikey_role_role_is_user_role_and_more"),
        ("sta", "0005_remove_datastream_data_archives_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="DataConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data_connection_type", models.CharField(max_length=255)),
                (
                    "extractor_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extractor_settings", models.JSONField(default=dict)),
                (
                    "transformer_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transformer_settings", models.JSONField(default=dict)),
                (
                    "loader_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("loader_settings", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_connections",
                        to="iam.workspace",
                    ),
                ),
            ],
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("paused", models.BooleanField(default=False)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("extractor_variables", models.JSONField(default=dict)),
                ("transformer_variables", models.JSONField(default=dict)),
                ("loader_variables", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="iam.workspace",
                    ),
                ),
                (
                    "data_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="etl.dataconnection",
                    ),
                ),
                (
                    "orchestration_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="etl.orchestrationsystem",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etl_task",
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="TaskMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_identifier", models.CharField(max_length=255)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="etl.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskMappingPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_identifier", models.CharField(max_length=255)),
                ("data_transformations", models.JSONField(default=dict)),
                (
                    "task_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="etl.taskmapping",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.task"
                    ),
                ),
            ],
        ),
        migrations.RunPython(update_settings_fields, reverse_update_settings_fields),
        migrations.RemoveField(
            model_name="datasource",
            name="orchestration_system",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="workspace",
        ),
        migrations.AlterField(
            model_name="orchestrationsystem",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orchestration_systems",
                to="iam.workspace",
            ),
        ),
        migrations.DeleteModel(
            name="DataArchive",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
