# Generated by Django 5.2.2 on 2026-03-06 21:11

from django.db import migrations


def fix_celery_task_names(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    task_name_map = {
        "etl.tasks.run_etl_task": "domains.etl.tasks.run_etl_task",
        "etl.tasks.cleanup_etl_task_runs": "domains.etl.tasks.cleanup_etl_task_runs",
    }
    for old_name, new_name in task_name_map.items():
        PeriodicTask.objects.filter(task=old_name).update(task=new_name)


def reverse_celery_task_names(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    task_name_map = {
        "domains.etl.tasks.run_etl_task": "etl.tasks.run_etl_task",
        "domains.etl.tasks.cleanup_etl_task_runs": "etl.tasks.cleanup_etl_task_runs",
    }
    for old_name, new_name in task_name_map.items():
        PeriodicTask.objects.filter(task=old_name).update(task=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ('etl', '0004_task_task_type_and_nullable_data_connection'),
    ]

    operations = [
        migrations.RunPython(fix_celery_task_names, reverse_celery_task_names),
    ]