# Generated by Django 5.2.2 on 2026-03-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_taskrun_latest_lookup_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnectionNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='etl.dataconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('data_connection', 'email'), name='unique_notification_recipient_per_data_connection')],
            },
        ),
    ]
