# Generated by Django 5.2.2 on 2026-03-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_dataconnectionnotificationrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='orchestration_system',
        ),
        migrations.DeleteModel(
            name='OrchestrationSystem',
        ),
    ]
