# Generated by Django 5.2.2 on 2026-05-26 19:15

import django.db.models.deletion
import uuid6
import json
from django.db import migrations, models


PLACEHOLDER_VARIABLE_TYPE_MAPPING = {
    "runTime": "run_time",
    "perTask": "per_task",
    "latestObservationTimestamp": "latest_observation_timestamp",
}

REVERSE_PLACEHOLDER_VARIABLE_TYPE_MAPPING = {v: k for k, v in PLACEHOLDER_VARIABLE_TYPE_MAPPING.items()}

VALID_RUN_STATUSES = {"PENDING", "STARTED", "SUCCESS", "FAILURE"}


def migrate_json_forward(apps, schema_editor):
    OldTask = apps.get_model("etl", "Task")
    OldTaskRun = apps.get_model("etl", "TaskRun")
    OldTaskMapping = apps.get_model("etl", "TaskMapping")
    OldTaskMappingPath = apps.get_model("etl", "TaskMappingPath")
    OldOrchestrationSystem = apps.get_model("etl", "OrchestrationSystem")

    DataConnection = apps.get_model("etl", "DataConnection")
    Datastream = apps.get_model("sta", "Datastream")

    EtlTask = apps.get_model("etl", "EtlTask")
    EtlMapping = apps.get_model("etl", "EtlMapping")
    BaseTask = apps.get_model("orchestration", "Task")
    BaseTaskRun = apps.get_model("orchestration", "TaskRun")
    Payload = apps.get_model("etl", "Payload")
    PlaceholderVariable = apps.get_model("etl", "PlaceholderVariable")

    # Halt if any non-INTERNAL orchestration systems exist
    invalid_orchestration_systems = list(
        OldOrchestrationSystem.objects
        .exclude(orchestration_system_type="INTERNAL")
        .values_list("orchestration_system_type", flat=True)
        .distinct()
    )
    if invalid_orchestration_systems:
        raise Exception(
            f"Migration aborted: non-INTERNAL orchestration system type(s) exist: {invalid_orchestration_systems}. "
            "Remove or convert these before migrating."
        )

    # Halt if any DataConnections are missing a workspace
    system_data_connections = DataConnection.objects.filter(workspace__isnull=True).count()
    if system_data_connections:
        raise Exception(
            f"Migration aborted: {system_data_connections} DataConnection(s) have no workspace. "
            "Assign a workspace to all DataConnections before migrating."
        )

    # Validate all task types before making any changes
    invalid_task_types = list(
        OldTask.objects
        .exclude(task_type__in=["ETL"])
        .values_list("task_type", flat=True)
        .distinct()
    )
    if invalid_task_types:
        raise Exception(
            f"Migration aborted: tasks exist with unsupported task_type(s): {invalid_task_types}. "
            "Only 'ETL' is supported. Resolve these before migrating."
        )

    # Migrate DataConnection fields from old JSON settings to dedicated fields,
    # and create Payload and PlaceholderVariable records.
    for dc in DataConnection.objects.all():
        extractor_settings = dc.extractor_settings or {}
        transformer_settings = dc.transformer_settings or {}
        timestamp = transformer_settings.get("timestamp") or {}

        dc.source_url = extractor_settings.get("sourceUri", "")

        timezone_mode = timestamp.get("timezoneMode", "")
        timestamp_format = timestamp.get("format", "")

        if timezone_mode == "embeddedOffset":
            dc.timezone_type = None
            dc.timezone = None
        elif timezone_mode == "fixedOffset":
            dc.timezone_type = "offset"
            dc.timezone = timestamp.get("timezone")
        elif timezone_mode == "daylightSavings":
            dc.timezone_type = "iana"
            dc.timezone = timestamp.get("timezone")
        elif timezone_mode in ("utc", "UTC"):
            if timestamp_format == "ISO8601":
                dc.timezone_type = None
                dc.timezone = None
            else:  # "naive", "custom", or unrecognized format — assume UTC
                dc.timezone_type = "offset"
                dc.timezone = "+0000"
        else:  # missing or unrecognized timezoneMode
            dc.timezone_type = None
            dc.timezone = None

        dc.save(update_fields=["source_url", "timezone", "timezone_type"])

        for pv in extractor_settings.get("placeholderVariables", []):
            old_pv_type = pv.get("type", "")
            old_pv_timestamp = pv.get("timestamp") or {}
            pv_type = PLACEHOLDER_VARIABLE_TYPE_MAPPING.get(old_pv_type)
            if pv_type is None:
                raise Exception(
                    f"Migration aborted: unsupported placeholder variable type '{old_pv_type}' "
                    f"on DataConnection {dc.id}. Supported types: {list(PLACEHOLDER_VARIABLE_TYPE_MAPPING)}."
                )
            PlaceholderVariable.objects.create(
                data_connection=dc,
                name=pv.get("name", ""),
                variable_type=pv_type,
                timestamp_format=(
                    old_pv_timestamp.get("customFormat") if old_pv_timestamp.get("format") == "custom" else None
                )
            )

        transformer_type = (dc.transformer_type or "").upper()
        if transformer_type == "CSV":
            Payload.objects.create(
                data_connection=dc,
                payload_type="CSV",
                timestamp_key=timestamp.get("key") or "",
                timestamp_format=timestamp.get("customFormat") if timestamp.get("format") == "custom" else None,
                header_row=transformer_settings.get("headerRow"),
                data_start_row=transformer_settings.get("dataStartRow"),
                delimiter=(
                    "\t" if transformer_settings.get("delimiter") == "\\t" else transformer_settings.get("delimiter")
                )
            )

        elif transformer_type == "JSON":
            Payload.objects.create(
                data_connection=dc,
                payload_type="JSON",
                timestamp_key=timestamp.get("key") or "",
                timestamp_format=timestamp.get("customFormat") if timestamp.get("format") == "custom" else None,
                jmespath=transformer_settings.get("JMESPath"),
            )

    for old_task in OldTask.objects.select_related("data_connection", "periodic_task").all():
        periodic_task = old_task.periodic_task

        # Detach periodic_task from old ETL task before linking to orchestration.Task.
        # Both models have a OneToOneField to PeriodicTask in different DB columns,
        # so the old column must be cleared first.
        if periodic_task:
            OldTask.objects.filter(id=old_task.id).update(periodic_task=None)

        # Create orchestration.Task preserving the original UUID so existing
        # PeriodicTask kwargs ({"task_id": "..."}) remain valid without update.
        base_task = BaseTask.objects.create(
            id=old_task.id,
            name=old_task.name,
            next_run_at=old_task.next_run_at,
            periodic_task_id=periodic_task.id if periodic_task else None,
        )

        # Migrate task runs, preserving original started_at via update() to bypass
        # auto_now_add on the new model.
        for old_run in OldTaskRun.objects.filter(task_id=old_task.id):
            status = old_run.status if old_run.status in VALID_RUN_STATUSES else "SUCCESS"
            new_run = BaseTaskRun.objects.create(
                task_id=base_task.id,
                status=status,
                finished_at=old_run.finished_at,
                result=old_run.result,
            )
            BaseTaskRun.objects.filter(id=new_run.id).update(started_at=old_run.started_at)

        if old_task.task_type == "ETL":
            task_variables = {
                **(old_task.extractor_variables or {}),
                **(old_task.transformer_variables or {}),
                **(old_task.loader_variables or {}),
            }
            # Insert directly into the child table to avoid Django's MTI save()
            # trying to re-INSERT/UPDATE the already-created parent Task row.
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO etl_etltask (task_ptr_id, data_connection_id, task_variables) "
                    "VALUES (%s, %s, %s)",
                    [str(base_task.pk), str(old_task.data_connection_id), json.dumps(task_variables)],
                )
            etl_task = EtlTask.objects.get(pk=base_task.pk)

            # Flatten TaskMapping + TaskMappingPath into EtlMapping.
            # data_transformations are intentionally not migrated.
            for old_mapping in OldTaskMapping.objects.filter(task_id=old_task.id):
                for old_path in OldTaskMappingPath.objects.filter(task_mapping_id=old_mapping.id):
                    try:
                        target_datastream = Datastream.objects.get(id=old_path.target_identifier)
                    except Datastream.DoesNotExist:
                        continue
                    EtlMapping.objects.create(
                        etl_task_id=etl_task.pk,
                        source_identifier=old_mapping.source_identifier,
                        target_datastream_id=target_datastream.id,
                    )


def migrate_json_reverse(apps, schema_editor):
    OldTask = apps.get_model("etl", "Task")
    OldTaskRun = apps.get_model("etl", "TaskRun")
    OldTaskMapping = apps.get_model("etl", "TaskMapping")
    OldTaskMappingPath = apps.get_model("etl", "TaskMappingPath")
    OldOrchestrationSystem = apps.get_model("etl", "OrchestrationSystem")

    DataConnection = apps.get_model("etl", "DataConnection")
    EtlTask = apps.get_model("etl", "EtlTask")
    EtlMapping = apps.get_model("etl", "EtlMapping")
    BaseTask = apps.get_model("orchestration", "Task")
    BaseTaskRun = apps.get_model("orchestration", "TaskRun")
    Payload = apps.get_model("etl", "Payload")
    PlaceholderVariable = apps.get_model("etl", "PlaceholderVariable")

    # Create a placeholder OrchestrationSystem; the original data is not recoverable.
    orchestration_system = OldOrchestrationSystem.objects.create(
        name="Internal",
        orchestration_system_type="INTERNAL",
    )

    # Restore old Task, TaskRun, TaskMapping, and TaskMappingPath records from EtlTask/EtlMapping.
    migrated_base_task_ids = []
    for etl_task in EtlTask.objects.select_related("task_ptr", "data_connection").all():
        base_task = etl_task.task_ptr

        # Transfer PeriodicTask link back to old Task; clear it from orchestration.Task
        # first to avoid a unique constraint conflict on the OneToOneField.
        periodic_task_id = base_task.periodic_task_id
        if periodic_task_id:
            BaseTask.objects.filter(pk=base_task.pk).update(periodic_task=None)

        old_task = OldTask.objects.create(
            id=base_task.id,
            name=base_task.name,
            task_type="ETL",
            next_run_at=base_task.next_run_at,
            workspace_id=etl_task.data_connection.workspace_id,
            data_connection=etl_task.data_connection,
            extractor_variables=etl_task.task_variables,
            transformer_variables={},
            loader_variables={},
            orchestration_system=orchestration_system,
            periodic_task_id=periodic_task_id,
        )

        # Restore task runs; use update() to preserve started_at past auto_now_add.
        for base_run in BaseTaskRun.objects.filter(task_id=base_task.id):
            new_old_run = OldTaskRun.objects.create(
                task_id=old_task.id,
                status=base_run.status,
                finished_at=base_run.finished_at,
                result=base_run.result,
            )
            OldTaskRun.objects.filter(pk=new_old_run.pk).update(started_at=base_run.started_at)

        # Restore TaskMapping + TaskMappingPath from EtlMapping, re-grouping by source_identifier.
        mapping_by_source = {}
        for etl_mapping in EtlMapping.objects.filter(etl_task_id=etl_task.pk):
            if etl_mapping.source_identifier not in mapping_by_source:
                old_mapping = OldTaskMapping.objects.create(
                    task_id=old_task.id,
                    source_identifier=etl_mapping.source_identifier,
                )
                mapping_by_source[etl_mapping.source_identifier] = old_mapping
            else:
                old_mapping = mapping_by_source[etl_mapping.source_identifier]
            OldTaskMappingPath.objects.create(
                task_mapping=old_mapping,
                target_identifier=str(etl_mapping.target_datastream_id),
            )

        migrated_base_task_ids.append(str(base_task.pk))

    # Delete orchestration.Task records via raw SQL to avoid Django's MTI historical-model
    # collector bug. Task runs must be deleted via ORM first (no deferred FK; plain constraint).
    # The etl_etltask and etl_etlmapping FKs are DEFERRABLE INITIALLY DEFERRED, so deleting
    # orchestration_task rows is safe — those tables are dropped later in the same transaction
    # by the DeleteModel operations, removing the constraints before they are checked.
    if migrated_base_task_ids:
        BaseTaskRun.objects.filter(task_id__in=migrated_base_task_ids).delete()
        placeholders = ",".join(["%s"] * len(migrated_base_task_ids))
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"DELETE FROM orchestration_task WHERE id IN ({placeholders})",
                migrated_base_task_ids,
            )

    # Restore DataConnection JSON settings from structured fields and related models.
    for dc in DataConnection.objects.prefetch_related("placeholder_variables").all():
        # Reconstruct extractor_settings from source_url and placeholder variables.
        placeholder_variables = []
        for pv in dc.placeholder_variables.all():
            pv_type = REVERSE_PLACEHOLDER_VARIABLE_TYPE_MAPPING.get(pv.variable_type, pv.variable_type)
            pv_entry = {"name": pv.name, "type": pv_type}
            if pv.timestamp_format:
                pv_entry["timestamp"] = {"format": "custom", "customFormat": pv.timestamp_format}
            placeholder_variables.append(pv_entry)

        extractor_settings = {
            "sourceUri": dc.source_url or "",
            "placeholderVariables": placeholder_variables,
        }

        # Reverse-map timezone_type/timezone back to old timezoneMode + optional timezone key.
        # Note: (None, None) is ambiguous — could have been embeddedOffset, utc+ISO8601, or
        # unrecognized. We use embeddedOffset as the best approximation.
        if dc.timezone_type == "iana":
            timezone_mode = "daylightSavings"
            tz_value = dc.timezone
        elif dc.timezone_type == "offset" and dc.timezone == "+0000":
            timezone_mode = "utc"
            tz_value = None
        elif dc.timezone_type == "offset":
            timezone_mode = "fixedOffset"
            tz_value = dc.timezone
        else:
            timezone_mode = "embeddedOffset"
            tz_value = None

        # Reconstruct timestamp settings from Payload.
        try:
            payload = dc.payload
        except Payload.DoesNotExist:
            payload = None

        timestamp_settings = {"timezoneMode": timezone_mode}
        if tz_value is not None:
            timestamp_settings["timezone"] = tz_value

        if payload:
            timestamp_settings["key"] = payload.timestamp_key or ""
            if payload.timestamp_format:
                timestamp_settings["format"] = "custom"
                timestamp_settings["customFormat"] = payload.timestamp_format

        # Reconstruct transformer_settings from Payload fields.
        if payload and payload.payload_type == "CSV":
            transformer_type = "CSV"
            transformer_settings = {
                "timestamp": timestamp_settings,
                "headerRow": payload.header_row,
                "dataStartRow": payload.data_start_row,
                "delimiter": "\\t" if payload.delimiter == "\t" else payload.delimiter,
            }
        elif payload and payload.payload_type == "JSON":
            transformer_type = "JSON"
            transformer_settings = {
                "timestamp": timestamp_settings,
                "JMESPath": payload.jmespath,
            }
        else:
            transformer_type = None
            transformer_settings = {"timestamp": timestamp_settings}

        dc.extractor_settings = extractor_settings
        dc.transformer_settings = transformer_settings
        dc.transformer_type = transformer_type
        dc.save(update_fields=["extractor_settings", "transformer_settings", "transformer_type"])

    # Delete structured records; their tables will be dropped by the subsequent
    # reverse of CreateModel operations.
    Payload.objects.all().delete()
    PlaceholderVariable.objects.all().delete()


def cleanup_etl_notification_schedules_reverse(apps, schema_editor):
    """
    Reverse-only cleanup: delete PeriodicTask rows (and their crontab/interval
    schedules) that are linked to DataConnectionNotification records before the
    table is dropped. Without this, those PeriodicTask rows would be permanently
    orphaned because the schema drop does not cascade to django_celery_beat tables.
    """

    DataConnectionNotification = apps.get_model("etl", "DataConnectionNotification")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")

    for notification in DataConnectionNotification.objects.select_related("periodic_task").all():
        pt = notification.periodic_task
        if not pt:
            continue

        if pt.crontab_id:
            crontab_id = pt.crontab_id
            PeriodicTask.objects.filter(pk=pt.pk).update(crontab=None)
            CrontabSchedule.objects.filter(pk=crontab_id).delete()

        if pt.interval_id:
            interval_id = pt.interval_id
            PeriodicTask.objects.filter(pk=pt.pk).update(interval=None)
            IntervalSchedule.objects.filter(pk=interval_id).delete()

        DataConnectionNotification.objects.filter(pk=notification.pk).update(periodic_task=None)
        pt.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('etl', '0007_dataconnectionnotificationrecipient'),
        ('iam', '0005_alter_permission_resource_type'),
        ('orchestration', '0001_initial'),
        ('sta', '0007_remove_thingfileattachment_download_token_and_more'),
    ]

    operations = [

        # Create new models and fields
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('payload_type', models.CharField(choices=[('CSV', 'Csv'), ('JSON', 'Json')], max_length=255)),
                ('timestamp_key', models.CharField(max_length=255)),
                ('timestamp_format', models.CharField(blank=True, max_length=255, null=True)),
                ('header_row', models.IntegerField(blank=True, null=True)),
                ('data_start_row', models.IntegerField(blank=True, null=True)),
                ('delimiter', models.CharField(blank=True, choices=[(',', 'Comma'), ('\t', 'Tab'), (';', 'Semicolon'),
                                                                    ('|', 'Pipe'), (' ', 'Space')],
                                               max_length=1, null=True)),
                ('jmespath', models.TextField(blank=True, null=True)),
                ('data_connection',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payload',
                                      to='etl.dataconnection')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceholderVariable',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(
                    choices=[('run_time', 'Run Time'), ('latest_observation_timestamp', 'Latest Observation Timestamp'),
                             ('per_task', 'Per Task')],
                    max_length=255
                )),
                ('data_connection',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_variables',
                                   to='etl.dataconnection')),
                ('timestamp_format', models.CharField(blank=True, max_length=255, null=True))
            ],
        ),
        migrations.CreateModel(
            name="EtlTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orchestration.task",
                    ),
                ),
                ("task_variables", models.JSONField(default=dict)),
                ("data_connection", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="etl_tasks",
                    to="etl.dataconnection",
                )),
            ],
            bases=("orchestration.task",),
        ),
        migrations.CreateModel(
            name="EtlMapping",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("source_identifier", models.CharField(max_length=255)),
                ("etl_task", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="etl_mappings",
                    to="etl.etltask",
                )),
                ("target_datastream", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="etl_mappings",
                    to="sta.datastream",
                )),
            ],
        ),

        # Add new fields to data connection model
        migrations.AddField(
            model_name='dataconnection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='source_url',
            field=models.TextField(default='http://www.example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='timezone_type',
            field=models.CharField(blank=True, choices=[('offset', 'Offset'), ('iana', 'Iana')],
                                   max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='auth_header_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='auth_header_value',
            field=models.TextField(blank=True, null=True),
        ),

        # Migrate JSON fields to new data model structure
        migrations.RunPython(migrate_json_forward, migrate_json_reverse),

        # Alter fields on existing models
        migrations.AlterField(
            model_name='dataconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connections',
                                    to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='data_connection_type',
            field=models.CharField(max_length=255, null=True, default='ETL'),
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='data_connection_type',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='extractor_settings',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='extractor_type',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='loader_settings',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='loader_type',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='transformer_settings',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='transformer_type',
        ),

        # Remove orchestration_system FK from Task before dropping both tables.
        # This ensures Django's migration state records Task without the field,
        # so the reverse can recreate OldTask records without providing it.
        migrations.RemoveField(model_name="task", name="orchestration_system"),

        # Drop old tables
        migrations.DeleteModel(name="TaskMappingPath"),
        migrations.DeleteModel(name="TaskMapping"),
        migrations.DeleteModel(name="TaskRun"),
        migrations.DeleteModel(name="Task"),
        migrations.DeleteModel(name="OrchestrationSystem"),
        migrations.DeleteModel(name="DataConnectionNotificationRecipient"),

        migrations.CreateModel(
            name='DataConnectionNotification',
            fields=[
                ('data_connection', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='notification',
                    serialize=False,
                    to='etl.dataconnection',
                )),
                ('periodic_task', models.OneToOneField(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='data_connection_notification',
                    to='django_celery_beat.periodictask',
                )),
            ],
            options={'app_label': 'etl'},
        ),
        migrations.CreateModel(
            name='DataConnectionNotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('notification', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='recipients',
                    to='etl.dataconnectionnotification',
                )),
            ],
            options={
                'app_label': 'etl',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('notification', 'email'),
                        name='unique_data_connection_notification_recipient_email',
                    )
                ],
            },
        ),

        # Reverse-only: clean up PeriodicTask rows linked to DataConnectionNotification
        # before the table is dropped. Runs as the first step on reverse (last in forward).
        migrations.RunPython(
            migrations.RunPython.noop,
            cleanup_etl_notification_schedules_reverse,
        ),
    ]
