# Generated by Django 5.2.2 on 2026-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_orchestration_tasks_from_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_end_anchor',
            field=models.CharField(blank=True, choices=[('latest_observation_timestamp', 'Latest Observation Timestamp'), ('run_time', 'Run Time'), ('fixed_timestamp', 'Fixed Timestamp')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_end_lookback',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_end_lookback_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_start_anchor',
            field=models.CharField(blank=True, choices=[('latest_observation_timestamp', 'Latest Observation Timestamp'), ('run_time', 'Run Time'), ('fixed_timestamp', 'Fixed Timestamp')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_start_lookback',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_start_lookback_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='data_ingestion_window_start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placeholdervariable',
            name='variable_type',
            field=models.CharField(choices=[('run_time', 'Run Time'), ('latest_observation_timestamp', 'Latest Observation Timestamp'), ('per_task', 'Per Task'), ('window_start', 'Data Ingestion Window Start'), ('window_end', 'Data Ingestion Window End')], max_length=255),
        ),
    ]
