# Generated by Django 5.2.2 on 2026-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_migrate_tasks_to_orchestration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='auth_header_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='auth_header_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
