# Generated by Django 6.0.7 on 2026-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_payload_data_ingestion_window_end_anchor_and_more'),
        ('sta', '0016_rename_metadata_table_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etlmapping',
            constraint=models.UniqueConstraint(fields=('target_datastream',), name='unique_etl_mapping_target_datastream', violation_error_message='This datastream is already mapped to by another task.'),
        ),
        migrations.AddConstraint(
            model_name='placeholdervariable',
            constraint=models.UniqueConstraint(fields=('data_connection', 'name', 'variable_type'), name='unique_placeholder_variable_name_and_type_per_data_connection', violation_error_message='A placeholder variable with this name and type already exists on this data connection.'),
        ),
    ]
