// Generated from colors.css by scripts/generate-vuetify-colors.mjs.
// Do not edit this file directly.
export const vuetifyColors = {
  'text-primary': '#1c1b1f',
  'text-secondary': '#49454f',
  'text-muted': '#9ca3af',
  background: '#f4f7fa',
  surface: '#ffffff',
  'surface-subtle': '#fcfdff',
  'surface-muted': '#eef3f8',
  'surface-floating': '#fffffff5',
  border: '#ced8e2',
  'input-border': '#cac4d0',
  primary: '#32649c',
  secondary: '#66ae5c',
  default: '#757575',
  danger: '#b3261e',
  'danger-bg': '#ffebee',
  delete: '#c62828',
  error: '#c62828',
  info: '#03a9f4',
  success: '#66ae5c',
  warning: '#ff9800',
} as const
