# Generated by Django 5.2.5 on 2025-11-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0004_datastreamfileattachmenttype_thingfileattachmenttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datastream",
            name="data_archives",
        ),
        migrations.RemoveField(
            model_name="datastream",
            name="data_source",
        ),
    ]
