# Generated by Django 5.2.5 on 2026-02-13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0005_remove_datastream_data_archives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thingfileattachment",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="thingfileattachment",
            name="download_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
