# Generated by Django 5.2.2 on 2026-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0006_thingfileattachment_rating_curve_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingfileattachment',
            name='download_token',
        ),
        migrations.AddField(
            model_name='datastreamfileattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thingfileattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
