# Generated by Django 6.0.7 on 2026-07-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_remove_workspacedeleteconfirmation_workspace_and_more'),
        ('sta', '0008_remove_observation_result_qualifiers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='observed_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.observedproperty'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='processing_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.processinglevel'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.sensor'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='sta.unit'),
        ),
        migrations.AlterField(
            model_name='datastreamfileattachment',
            name='datastream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastream_file_attachments', to='sta.datastream'),
        ),
        migrations.AlterField(
            model_name='datastreamtag',
            name='datastream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastream_tags', to='sta.datastream'),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observed_properties', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='iam.workspace'),
        ),
    ]
