# Generated by Django 6.0.7 on 2026-07-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_remove_workspacedeleteconfirmation_workspace_and_more'),
        ('sta', '0009_alter_datastream_observed_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglevel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_levels', to='iam.workspace'),
        ),
        migrations.AlterField(
            model_name='resultqualifier',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_qualifiers', to='iam.workspace'),
        ),
    ]
