# Generated by Django 6.0.7 on 2026-07-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0010_alter_processinglevel_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='thingfileattachment',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_file_attachments', to='sta.thing'),
        ),
        migrations.AlterField(
            model_name='thingtag',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_tags', to='sta.thing'),
        ),
    ]
