# Generated by Django 6.0.7 on 2026-09-22 15:33

from importlib import import_module

from django.db import migrations, models
from django.db.models.functions import Length, Substr


search_trigger = import_module(
    "core.sta.migrations.0017_datastream_search_vector_method_search_vector_and_more"
)._search_vector_trigger_sql

# PostgreSQL will not alter a column referenced by a trigger's WHEN clause.
# Remove these triggers before changing field types, then rebuild and backfill.
OLD_SEARCH_FIELDS = {
    "sta_method": {
        "name": "A", "description": "B", "definition": "B", "type": "C",
        "sensor_model": "C", "sensor_model_manufacturer": "C",
        "sensor_model_definition": "C",
    },
    "sta_observedproperty": {
        "name": "A", "definition": "B", "description": "B", "type": "C", "code": "C",
    },
    "sta_processinglevel": {
        "name": "A", "description": "B", "definition": "B", "code": "C",
    },
    "sta_resultqualifier": {"description": "A", "code": "C"},
    "sta_unit": {"name": "A", "definition": "B", "symbol": "C", "type": "C"},
}
NEW_SEARCH_FIELDS = {
    **OLD_SEARCH_FIELDS,
    "sta_method": {**OLD_SEARCH_FIELDS["sta_method"], "code": "C"},
    "sta_resultqualifier": {"name": "A", "description": "B", "code": "C"},
}


def check_existing_lengths(apps, schema_editor):
    # PostgreSQL's varchar casts silently truncate. Only processing-level names
    # are intentionally truncated; external identifiers and URLs must be retained.
    for model, field, limit in [
        ("ObservedProperty", "code", 255),
        ("ObservedProperty", "definition", 2000),
        ("ProcessingLevel", "definition", 2000),
        ("Unit", "definition", 2000),
    ]:
        oversized = (
            apps.get_model("sta", model).objects.using(schema_editor.connection.alias)
            .annotate(field_length=Length(field))
            .filter(field_length__gt=limit)
        )
        if oversized.exists():
            raise ValueError(
                f"{model}.{field} contains values longer than {limit} characters. "
                "Shorten those values before rerunning the metadata migration."
            )


def populate_names(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model("sta", "ProcessingLevel").objects.using(alias).update(
        name=Substr("description", 1, 255)
    )
    # Observation arrays already contain these strings and need no rewrite.
    apps.get_model("sta", "ResultQualifier").objects.using(alias).update(
        name=models.F("code")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_workspace_search_vector_and_more'),
        ('sta', '0017_datastream_search_vector_method_search_vector_and_more'),
    ]

    operations = [
        migrations.RunPython(check_existing_lengths, migrations.RunPython.noop),
        *[
            migrations.RunSQL(
                sql=search_trigger(table, fields)[0].reverse_sql,
                reverse_sql=search_trigger(table, fields)[0].sql,
            )
            for table, fields in OLD_SEARCH_FIELDS.items()
        ],
        migrations.RemoveConstraint(
            model_name='resultqualifier',
            name='unique_scoped_result_qualifier_code',
        ),
        migrations.AddField(
            model_name='resultqualifier',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='definition',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='definition',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processinglevel',
            name='definition',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resultqualifier',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='definition',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.RunPython(populate_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resultqualifier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='resultqualifier',
            constraint=models.UniqueConstraint(fields=('name', 'workspace_id'), name='unique_scoped_result_qualifier_name', nulls_distinct=False),
        ),
        *[
            operation
            for table, fields in NEW_SEARCH_FIELDS.items()
            for operation in search_trigger(table, fields)
        ],
    ]
