# Generated by Django 6.0.7 on 2026-09-22 16:31

from importlib import import_module

from django.db import migrations, models
from django.db.models.functions import Length


metadata_migration = import_module("core.sta.migrations.0018_standardize_workspace_metadata")
search_trigger = metadata_migration.search_trigger
SEARCH_FIELDS = {
    table: metadata_migration.NEW_SEARCH_FIELDS[table]
    for table in ("sta_method", "sta_observedproperty")
}


def check_type_lengths(apps, schema_editor):
    properties = apps.get_model("sta", "ObservedProperty").objects.using(
        schema_editor.connection.alias
    )
    if properties.annotate(type_length=Length("type")).filter(type_length__gt=255).exists():
        raise ValueError(
            "ObservedProperty.type contains values longer than 255 characters. "
            "Shorten those values before rerunning the metadata migration."
        )



class Migration(migrations.Migration):

    dependencies = [
        ('sta', '0018_standardize_workspace_metadata'),
    ]

    operations = [
        migrations.RunPython(check_type_lengths, migrations.RunPython.noop),
        # Drop triggers whose WHEN clauses reference columns being altered.
        *[
            migrations.RunSQL(
                sql=search_trigger(table, fields)[0].reverse_sql,
                reverse_sql=search_trigger(table, fields)[0].sql,
            )
            for table, fields in SEARCH_FIELDS.items()
        ],
        migrations.AlterField(
            model_name='method',
            name='sensor_model_definition',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observedproperty',
            name='type',
            field=models.CharField(max_length=255),
        ),
        *[
            operation
            for table, fields in SEARCH_FIELDS.items()
            for operation in search_trigger(table, fields)
        ],
    ]
