# Generated by Django 5.2.2 on 2025-08-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.CreateModel(
            name="InstanceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_about_information", models.BooleanField(default=False)),
                (
                    "about_page_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("about_page_text", models.TextField(blank=True, null=True)),
                (
                    "terms_of_use_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "privacy_policy_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("copyright", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Instance Configuration",
                "verbose_name_plural": "Instance Configuration",
            },
        ),
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("basemap", "Basemap"), ("overlay", "Overlay")],
                        max_length=255,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("source", models.CharField(max_length=255)),
                ("attribution", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Map Layer",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_clarity_analytics", models.BooleanField(default=False)),
                (
                    "clarity_project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instance_configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytics_configuration",
                        to="web.instanceconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Configuration",
                "verbose_name_plural": "Analytics Configuration",
            },
        ),
        migrations.CreateModel(
            name="MapConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_latitude",
                    models.DecimalField(decimal_places=16, default=39, max_digits=22),
                ),
                (
                    "default_longitude",
                    models.DecimalField(decimal_places=16, default=-100, max_digits=22),
                ),
                ("default_zoom_level", models.IntegerField(default=4)),
                (
                    "elevation_service",
                    models.CharField(
                        choices=[
                            ("openElevation", "Open Elevation"),
                            ("google", "Google"),
                        ],
                        default="openElevation",
                        max_length=255,
                    ),
                ),
                (
                    "geo_service",
                    models.CharField(
                        choices=[("nominatim", "Nominatim"), ("google", "Google")],
                        default="nominatim",
                        max_length=255,
                    ),
                ),
                (
                    "instance_configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_configuration",
                        to="web.instanceconfiguration",
                    ),
                ),
                (
                    "default_base_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_base_layer",
                        to="web.maplayer",
                    ),
                ),
                (
                    "default_satellite_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_satellite_layer",
                        to="web.maplayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Map Configuration",
                "verbose_name_plural": "Map Configuration",
            },
        ),
    ]
