# Generated by Django 5.2 on 2025-07-22 19:39

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="observation",
            name="sta_observa_id_5779e2_idx",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Step 1: Add datastream_id, phenomenon_time unique constraint if it doesn't exist
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'unique_datastream_id_phenomenon_time'
                      ) THEN
                        ALTER TABLE sta_observation
                        ADD CONSTRAINT unique_datastream_id_phenomenon_time
                        UNIQUE (datastream_id, phenomenon_time);
                      END IF;
                    END$$;
                    """,
                    reverse_sql="""
                    ALTER TABLE sta_observation
                    DROP CONSTRAINT IF EXISTS unique_datastream_id_phenomenon_time;
                    """,
                ),
                # Step 2: Drop the old PK constraint
                migrations.RunSQL(
                    """
                    ALTER TABLE sta_observation
                    DROP CONSTRAINT sta_observation_pkey;
                    """,
                    reverse_sql="""
                    ALTER TABLE sta_observation
                    ADD CONSTRAINT sta_observation_pkey
                    PRIMARY KEY (datastream_id, phenomenon_time);
                    """,
                ),
                # Step 3: Promote `id` to PK using existing index if present
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                      IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE tablename = 'sta_observation'
                          AND indexname = 'sta_observation_pkey_index'
                      ) THEN
                        -- Use existing index to create PK constraint
                        ALTER TABLE sta_observation
                        ADD CONSTRAINT sta_observation_pkey
                        PRIMARY KEY USING INDEX sta_observation_pkey_index;
                      ELSE
                        -- Create the named unique index, then use it for PK
                        CREATE UNIQUE INDEX sta_observation_pkey_index ON sta_observation(id);
                        ALTER TABLE sta_observation
                        ADD CONSTRAINT sta_observation_pkey
                        PRIMARY KEY USING INDEX sta_observation_pkey_index;
                      END IF;
                    END$$;
                    """,
                    reverse_sql="""
                    ALTER TABLE sta_observation
                    DROP CONSTRAINT sta_observation_pkey;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="observation",
                    name="pk",
                ),
                migrations.AddConstraint(
                    model_name="observation",
                    constraint=models.UniqueConstraint(
                        fields=("datastream_id", "phenomenon_time"),
                        name="unique_datastream_id_phenomenon_time",
                    ),
                ),
                migrations.AlterField(
                    model_name="observation",
                    name="id",
                    field=models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
