# Generated by Django 5.2.5 on 2025-10-27 17:28

import django.db.models.deletion
import domains.iam.models.utils
import domains.sta.models.datastream
import domains.sta.models.thing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sta", "0003_observation_result_qualifiers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state',
            new_name='admin_area_1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='county',
            new_name='admin_area_2',
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="photo",
            new_name="file_attachment",
        ),
        migrations.AddField(
            model_name="photo",
            name="file_attachment_type",
            field=models.CharField(default="Photo", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="photo",
            name="thing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="thing_file_attachments",
                to="sta.thing",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="thing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="thing_tags",
                to="sta.thing",
            ),
        ),
        migrations.RenameModel(
            old_name="Tag",
            new_name="ThingTag",
        ),
        migrations.RenameModel(
            old_name="Photo",
            new_name="ThingFileAttachment",
        ),
        migrations.CreateModel(
            name="FileAttachmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DatastreamFileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file_attachment",
                    models.FileField(
                        upload_to=domains.sta.models.datastream.datastream_file_attachment_storage_path
                    ),
                ),
                ("file_attachment_type", models.CharField(max_length=200)),
                (
                    "datastream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="datastream_file_attachments",
                        to="sta.datastream",
                    ),
                ),
            ],
            options={
                "unique_together": {("datastream", "name")},
            },
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
        migrations.CreateModel(
            name="DatastreamTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "datastream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="datastream_tags",
                        to="sta.datastream",
                    ),
                ),
            ],
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
    ]
