# Generated by Django 5.2b1 on 2025-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"), name="unique_workspace_name_per_owner"
            ),
        ),
    ]
