# Generated by Django 5.2.5 on 2025-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_role_is_apikey_role_role_is_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("*", "All"),
                    ("APIKey", "API Key"),
                    ("Role", "Role"),
                    ("Collaborator", "Collaborator"),
                    ("Task", "Task"),
                    ("DataConnection", "Data Connection"),
                    ("OrchestrationSystem", "Orchestration System"),
                    ("Thing", "Thing"),
                    ("Datastream", "Datastream"),
                    ("Observation", "Observation"),
                    ("Sensor", "Sensor"),
                    ("ObservedProperty", "Observed Property"),
                    ("ProcessingLevel", "Processing Level"),
                    ("Unit", "Unit"),
                    ("ResultQualifier", "Result Qualifier"),
                ],
                max_length=50,
            ),
        ),
    ]
