# Generated by Django 5.2 on 2025-05-05 17:30

import django.db.models.deletion
import django.utils.timezone
import domains.iam.models.utils
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_workspace_unique_workspace_name_per_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_apikey_role",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="is_user_role",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("*", "All"),
                    ("APIKey", "API Key"),
                    ("Role", "Role"),
                    ("Collaborator", "Collaborator"),
                    ("DataSource", "Data Source"),
                    ("DataArchive", "Data Archive"),
                    ("OrchestrationSystem", "Orchestration System"),
                    ("Thing", "Thing"),
                    ("Datastream", "Datastream"),
                    ("Observation", "Observation"),
                    ("Sensor", "Sensor"),
                    ("ObservedProperty", "Observed Property"),
                    ("ProcessingLevel", "Processing Level"),
                    ("Unit", "Unit"),
                    ("ResultQualifier", "Result Qualifier"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("hashed_key", models.CharField(editable=False, max_length=128)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="apikeys",
                        to="iam.role",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="apikeys",
                        to="iam.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
            bases=(models.Model, domains.iam.models.utils.PermissionChecker),
        ),
    ]
