version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: hydroserver_nginx
    ports:
      - "80:80" # HydroServer port
    volumes:
      - ${HS_STATICFILES}:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bridge
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP port
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
